version: "3.4"

services:
  one-hub:
    image: one-hub
    container_name: one-hub
    restart: always
    command: --log-dir /app/logs
    ports:
      - "3000:3000"
    volumes:
      - ./data/onehub:/data
      - ./logs:/app/logs
    environment:
      - SQL_DSN=onehub:123456@tcp(db:3306)/one-hub
      - REDIS_CONN_STRING=redis://redis
      - SESSION_SECRET=random_string
      - TZ=Asia/Shanghai
    depends_on:
      - redis
      - db

  redis:
    image: redis:latest
    container_name: redis
    restart: always

  db:
    image: mysql:8.2.0
    restart: always
    container_name: mysql
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: "OneHUB@acantrell"
      MYSQL_USER: onehub
      MYSQL_PASSWORD: "123456"
      MYSQL_DATABASE: one-hub
